baseurl = "https://taubin.pro"
languageCode = "en"
title = "Taubin | Pro"
theme = "hucore"
date = ""
copyright = "&copy; 2017 | Follow on <a href=\"https://twitter.com/taubin\" target=\"_blank\">Twitter</a> | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"
#disqusShortname = "shortname"
googleAnalytics = "trackingcode"
newContentEditor = "nano"
pygmentsStyle = "native"


[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Taubin's Tech Blog"
keywords = [""]
author = "Dustin Plunkett"
sharingicons = true

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/taubin"
fa_icon = "fa-github"

[[params.social]]
url = "https://gitlab.com/dustin_p"
fa_icon = "fa-gitlab"

[[params.social]]
url = "https://twitter.com/taubin"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://facebook.com/CraftBeerSnob"
fa_icon = "fa-facebook-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

